name: fadil_driweather
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8
  weather_icons: 3.0.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  intl: ^0.18.1
  logging: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/data/indonesia_cities.json
    - assets/picture/cloudy.png
    - assets/picture/drizzle.png
    - assets/picture/light_rain.png
    - assets/picture/mostly_cloudy.png
    - assets/picture/sun.png
    - assets/picture/thunder.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/picture/cloudy.png"
